### ISSUE TITLE
Cannot find preview item for proxy

### ISSUE THREAD

**Issue by XinLok007** [ishaq/SimplePDF#2]
Thank you for this great code, really appreciate your wonderful job.
There is a warning when i run the application:
SimplePDFDemo[1121:52299] Cannot find preview item for proxy: <QLPreviewItemProxy: 0x7fb9fb100a10> - SimplePDF 1.pdf (0)

any advise?

**Comment by ishaq** [comment]
Thanks @XinLok007, I haven't updated this code in a while, so it's probably some outdated API. I'll look at it over the weekend.

**Comment by ishaq** [comment]
@XinLok007 I looked at the warning, can't figure out how to fix it. However, this warning is 1) not related to the SimplePDF lib itself, 2) is probably harmless since the PDF still gets displayed in the preview controller.

So, you can use the library without worrying about it. I'll keep the ticket open to keep it on my radar.

**Comment by XinLok007** [comment]
Thank you man, in anyway your codes is great codes.

**Comment by yestay90** [comment]
anyone solved this issue ?
