### ISSUE TITLE
Error in installing Podfile

### ISSUE THREAD

**Issue by Razie7** [ishaq/SimplePDF#22]
Hi Muhammed
I would like to test your SimplePDF. 

I downloaded the ZIP file of ur project but when I install the Podfile I get this:

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `SimplePDF_Example`..
# from /Users/Desktop/SimplePDF-master/Example/Podfile:4

 #  -------------------------------------------
 #  

>  target 'SimplePDF_Example', :exclusive => true do
>  #    pod 'SimplePDFSwift', :path => '../'

note: 
The SImplePDF-Master directory has no either SimplePDF_Example nor SimplePDF_Tests files.

Am I missing something here? 

Also, when I add  import SimplePDFSwift  to my xcodeproject it says "no such Module "SimplePDFSwift"
eventhough the I successfully installed the podfile. 
i used this in the podfile:

```
  use_frameworks!
  target "mytestfile" do
            pod 'SimplePDFSwift'
```

end

Thanks for your help!

**Comment by ishaq** [comment]
The first error is something wrong with your Podfile, please check cocoa pods docs for that.

the second error is because you need to import _SimplePDF_ (the pod is called _SimplePDFSwift_ but the module is _SimplePDF_, When I had tried to submit the pod, I found out that the name _SimplePDF_ was taken, so I renamed it to _SimplePDFSwift_)
