### ISSUE TITLE
pdf.addView(view) Position

### ISSUE THREAD

**Issue by Razie7** [ishaq/SimplePDF#25]
Salam!
Thanks for your great work! I found your code very useful. 

I am trying to add Signature (small rectangle UIView) at the bottom left of the PDF. Right now every time I use pdf.addView(Signature), it goes at the very top left of the page?  

My question is how could I make it to the bottom?

I know you mentioned that the UIView must be added to an active view hierarchy- off-screen- could you please provide more information on how to that? I tried to add views and sub views with different position values programmatically, but I always get the UIview at the top left. 

please forgive my ignorance if my question is simple. I am still new and learning about swift development! 

BarakaAlloho feek! 

Regards,

**Comment by Razie7** [comment]
Update:
I got around it by converting my UIview to a  temporary image then I added it to my pdf using add.images. but i am just curious about how to change UIview position in the PDF 

Thanks

**Comment by ishaq** [comment]
Thank you for your kind words @Razie7 

As for the view, it is expected behavior. The view is always laid out on the full page starting from the top of the page. So if your view is very small. you should put it in the bottom-left corner of a bigger white view and call addView on that bigger view. It will make sure that the signature view appears at bottom-left.

feel free to let me know if it is still confusing.

Fi-Amaan-i-llah

**Comment by Razie7** [comment]
Thank you! 
I tried I put my target view in a bigger view but it was still showing up in the top corner.
