### ISSUE TITLE
Remove number from Pdf title.

### ISSUE THREAD

**Issue by iOS-Architect** [ishaq/SimplePDF#31]
Hello! Thanks for the nice plugin. I am facing an issue is that everytime i reopen simulator it increment a number in pdftitle. Check the image for reference. It was added 69 in PDF title at the moment. I want to remove that number from the navigation title. 

![pdf](https://cloud.githubusercontent.com/assets/10369328/24955418/c54666e8-1f9c-11e7-8738-823c38fd4d50.png)

**Comment by iOS-Architect** [comment]
Also there were some error logs in console even though PDF generating fine. Any one else facing that issue.

![screen shot 2017-04-12 at 5 21 49 pm](https://cloud.githubusercontent.com/assets/10369328/24957269/9796d87e-1fa4-11e7-89be-2ed93dc95cf2.png)

**Comment by jaceee** [comment]
The logs are a bug in iOS 10, fixed in iOS 10.2.
Reference: [steipete on Twitter](https://twitter.com/steipete/status/764446752472698880)

**Comment by iOS-Architect** [comment]
Thanks. Any help for the first issue i.e the title one.

**Comment by ishaq** [comment]
@ImranIB the file name in the title is the name of the temporary file that it generates, it counts on the developer to save it to some place safe (where it wouldn't be deleted by the OS automatically) before opening it.

If you meant that there should be an `overwrite` flag so that it does not generate unique name for temp files, that could be a simple fix and I would welcome changes (do not have time in near future to work on it myself).

**Comment by iOS-Architect** [comment]
Thanks
